import { atom } from 'recoil';
import { GroupMember, MenuInfo, Task, Tasks } from '@/typings/project.ts';

export const taskAll = atom<Task[]>({
  key: 'taskAll',
  default: [
    {
      id: 0,
      dragId: '0',
      name: 'task1',
      status: 'before',
      group_id: 1,
      group: '개발팀',
      p_id: null,
      menu: '요구사항',
      targetMember: 'OCI(오채영)',
    },
    {
      id: 1,
      dragId: '1',
      name: 'task2',
      status: 'before',
      group_id: 1,
      group: '개발팀',
      p_id: null,
      menu: '요구사항',
      targetMember: 'OCI(오채영)',
    },
    {
      id: 2,
      dragId: '2',
      name: 'task3',
      status: 'before',
      group_id: 2,
      group: '마케팅팀',
      p_id: null,
      menu: '요구사항',
      targetMember: 'OCI(오채영)',
    },
    {
      id: 3,
      dragId: '3',
      name: 'task4',
      status: 'going',
      group_id: 2,
      group: '마케팅팀',
      p_id: null,
      menu: '개발',
      targetMember: 'OCI(오채영)',
    },
    {
      id: 4,
      dragId: '4',
      name: 'task5',
      status: 'going',
      group_id: 3,
      group: '홍보팀',
      p_id: null,
      menu: '개발',
      targetMember: 'OCI(오채영)',
    },
    {
      id: 5,
      dragId: '5',
      name: 'task6',
      status: 'going',
      group_id: 3,
      group: '홍보팀',
      p_id: null,
      menu: '요구사항',
      targetMember: 'OCI(오채영)',
    },
    {
      id: 6,
      dragId: '6',
      name: 'task7',
      status: 'done',
      group_id: 1,
      group: '개발팀',
      p_id: null,
      menu: '요구사항',
      targetMember: 'OCI(오채영)',
    },
    {
      id: 7,
      dragId: '7',
      name: 'task8',
      status: 'before',
      group_id: 2,
      group: '마케팅',
      p_id: null,
      menu: '요구사항',
      targetMember: 'OCI(오채영)',
    },
    {
      id: 8,
      dragId: '8',
      name: 'task9',
      status: 'done',
      group_id: 5,
      group: '백엔드',
      p_id: 1,
      menu: '개발',
      targetMember: 'OCI(오채영)',
    },
    {
      id: 9,
      dragId: '9',
      name: 'task10',
      status: 'done',
      group_id: 4,
      group: '프론트엔드',
      p_id: 1,
      menu: '요구사항',
      targetMember: 'OCI(오채영)',
    },
    {
      id: 10,
      dragId: '10',
      name: 'task11',
      status: 'before',
      group_id: 4,
      group: '프론트엔드',
      p_id: 1,
      menu: '개발',
      targetMember: 'OCI(오채영)',
    },
    {
      id: 11,
      dragId: '9',
      name: 'task10',
      status: 'done',
      group_id: 4,
      group: '프론트엔드',
      p_id: 1,
      menu: '요구사항',
      targetMember: 'OCI(오채영)',
    },
    {
      id: 12,
      dragId: '10',
      name: 'task11',
      status: 'before',
      group_id: 4,
      group: '프론트엔드',
      p_id: 1,
      menu: '개발',
      targetMember: 'OCI(오채영)',
    },
  ],
});
export const taskState = atom<Tasks>({
  key: 'task',
  default: {
    before: [
      {
        id: 0,
        dragId: '0',
        name: 'task1',
        status: 'before',
        group_id: 1,
        group: '개발팀',
        p_id: null,
        menu: '요구사항',
        targetMember: 'OCI(오채영)',
      },
      {
        id: 1,
        dragId: '1',
        name: 'task2',
        status: 'before',
        group_id: 1,
        group: '개발팀',
        p_id: null,
        menu: '요구사항',
        targetMember: 'OCI(오채영)',
      },
      {
        id: 2,
        dragId: '2',
        name: 'task3',
        status: 'before',
        group_id: 2,
        group: '마케팅팀',
        p_id: null,
        menu: '요구사항',
        targetMember: 'OCI(오채영)',
      },
      {
        id: 7,
        dragId: '7',
        name: 'task8',
        status: 'before',
        group_id: 2,
        group: '마케팅',
        p_id: null,
        menu: '요구사항',
        targetMember: 'OCI(오채영)',
      },
      {
        id: 10,
        dragId: '10',
        name: 'task11',
        status: 'before',
        group_id: 4,
        group: '프론트엔드',
        p_id: 1,
        menu: '개',
        targetMember: 'OCI(오채영)',
      },
      {
        id: 11,
        dragId: '11',
        name: 'task12',
        status: 'before',
        group_id: 5,
        group: '백엔드',
        p_id: 1,
        menu: '요구사항',
        targetMember: 'OCI(오채영)',
      },
    ],
    going: [
      {
        id: 3,
        dragId: '3',
        name: 'task4',
        status: 'going',
        group_id: 2,
        group: '마케팅팀',
        p_id: null,
        menu: '개',
        targetMember: 'OCI(오채영)',
      },
      {
        id: 4,
        dragId: '4',
        name: 'task5',
        status: 'going',
        group_id: 3,
        group: '홍보팀',
        p_id: null,
        menu: '개',
        targetMember: 'OCI(오채영)',
      },
      {
        id: 5,
        dragId: '5',
        name: 'task6',
        status: 'going',
        group_id: 3,
        group: '홍보팀',
        p_id: null,
        menu: '요구사항',
        targetMember: 'OCI(오채영)',
      },
      {
        id: 12,
        dragId: '12',
        name: 'task13',
        status: 'going',
        group_id: 6,
        group: '프론트엔드',
        p_id: 2,
        menu: '개',
        targetMember: 'OCI(오채영)',
      },
    ],
    done: [
      {
        id: 6,
        dragId: '6',
        name: 'task7',
        status: 'done',
        group_id: 1,
        group: '개발팀',
        p_id: null,
        menu: '요구사항',
        targetMember: 'OCI(오채영)',
      },
      {
        id: 8,
        dragId: '8',
        name: 'task9',
        status: 'done',
        group_id: 5,
        group: '백엔드',
        p_id: 1,
        menu: '개발',
        targetMember: 'OCI(오채영)',
      },
      {
        id: 9,
        dragId: '9',
        name: 'task10',
        status: 'done',
        group_id: 4,
        group: '프론트엔드',
        p_id: 1,
        menu: '요구사항',
        targetMember: 'OCI(오채영)',
      },
    ],
  },
});

export const menuListData = atom<MenuInfo[]>({
  key: 'menuList',
  default: [
    { id: 1, name: '결과물' },
    { id: 2, name: '요구사항' },
    { id: 3, name: '개발' },
    { id: 4, name: '배포' },
    { id: 5, name: '개발2' },
    { id: 6, name: '배포2' },
  ],
});

// 그룹 멤버 리스트
export const groupMemberList = atom<GroupMember[][]>({
  key: 'groupMemberList',
  default: [
    [
      {
        position: 'master',
        profile: null,
        nickName: 'Crong',
        name: '권오현',
        email: 'qhslsl@gmail.com',
        group: 'Frontend',
      },
      {
        position: 'leader',
        profile: 'https://tech.cloudmt.co.kr/2023/02/27/juunini-why-argo/images/argo.webp',
        nickName: 'OCI',
        name: '오채영',
        email: '1234@gmail.com',
        group: 'Frontend',
      },
    ],
    [
      {
        position: 'leader',
        profile: 'https://tech.cloudmt.co.kr/2023/02/27/juunini-why-argo/images/argo.webp',
        nickName: 'Argo',
        name: '박은령',
        email: 'q123124@gmail.com',
        group: 'Backend',
      },
      {
        position: 'member',
        profile:
          'https://w7.pngwing.com/pngs/276/1019/png-transparent-sid-sloth-scrat-ice-age-the-sloth-buckle-free-thumbnail.png',
        nickName: '젠킨스',
        name: '장준',
        email: '123124@gmail.com',
        group: 'Backend',
      },
      {
        position: 'member',
        profile:
          'https://w7.pngwing.com/pngs/276/1019/png-transparent-sid-sloth-scrat-ice-age-the-sloth-buckle-free-thumbnail.png',
        nickName: '나무늘보',
        name: '김윤정',
        email: 'fasfs@gmail.com',
        group: 'Backend',
      },
    ],
    [
      {
        position: 'member',
        profile: null,
        nickName: '2426',
        name: '빈지노',
        email: '2426@gmail.com',
        group: null,
      },
      {
        position: 'member',
        profile:
          'https://w7.pngwing.com/pngs/276/1019/png-transparent-sid-sloth-scrat-ice-age-the-sloth-buckle-free-thumbnail.png',
        nickName: '개리',
        name: '강개리',
        email: 'rissang@gmail.com',
        group: null,
      },
    ],
  ],
});
